openapi: 3.0.0
info:
  title: Fitch API
  description: This provide the FITCH API documentation
  version: 1.0.0
servers:
  - url: http://localhost:3000/
paths:
  /swaggerAPI/docs:
    get:
      description: ''
      responses:
        default:
          description: ''
  /swaggerAPI/user/:
    get:
      tags:
        - Users
      description: ''
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    post:
      description: ''
      responses:
        '201':
          description: Created
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  example: any
                username:
                  example: any
                email:
                  example: any
  /swaggerAPI/otherUser/:
    get:
      tags:
        - Users
      description: ''
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    post:
      description: ''
      responses:
        '201':
          description: Created
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  example: any
                username:
                  example: any
                email:
                  example: any
